# purpose: to describe to the cert manager where it should go when
#   attempting to get a certificate
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  # named after our issuer
  name: letencrypt-prod
spec:
  acme:
    # link to the letsencrypt apit to use
    server: https://acme-v02.api.letsencrypt.org/directory
    # not used by the process, but is a requirement from letsencrypt
    email: "codingwithcodi@gmail.com"
    privatKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
        ingress:
          class: nginx